# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "Sajia" ]
  pull_request:
    branches: [ "Sajia" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./ebook-client/package-lock.json
    - run: git config --global url."git@github.com:".insteadOf git://github.com/
    - run: npm install --legacy-peer-deps
      working-directory: ./ebook-client
    - run: npm ci
      working-directory: ./ebook-client
    - run: npm run build --if-present
      working-directory: ./ebook-client
    - run: npm run dev -- --host
      working-directory: ./ebook-client
